name: PR Check

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    name: Run TypeScript type check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Run NPM outdated check
        uses: gh640/npm-outdated-action@0864ddcc8ba15bbb484dae29d61d9dd49efad3ae
        id: npm-outdated

      - name: Comment outdated dependencies on PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.npm-outdated.outputs.summary }}
